server:
  port: 8059  # Porta do servidor
  debug: true  # Modo debug

layout:
  background_color: "#fff4cc"  # Cor de fundo do layout
  padding: "20px"
  max_height: "100vh"  # Altura máxima do vídeo
  font_color: "#333333"  # Cor da fonte

video_player:
  width: "100%"
  height: "auto"
ativities: [
                    'SITTING',
                    'STANDING',
                    'WALKING_UPSTAIRS',
                    'WALKING_DOWNSTAIRS',
                    'WALKING_SPONTANEOUS',
                    'RUN',
                    'WALKING_FAST',
                    'ELEVATOR_UP',
                    'ELEVATOR_DOWN',
                    'WALKING_IN_DOOR',
                    'DISTRACTED_WALKING',
                    "STANDING_SITTING",
                    "STANDING_WALKING",
                    "STANDING_UPSTAIRS",
                    "STANDING_DOWNSTAIRS",
                    "STANDING_WALKING_SPONTANEOUS",
                    "STANDING_RUN",
                    "STANDING_WALKING_FAST",
                    "STANDING_ELEVATOR_UP",
                    "STANDING_ELEVATOR_DOWN",
                    "STANDING_WALKING_IN_DOOR",
                    "STANDING_DISTRACTED_WALKING",
                    "SITTING_STANDING",
                    "WALKING_STANDING",
                    "UPSTAIRS_STANDING",
                    "DOWNSTAIRS_STANDING",
                    "WALKING_SPONTANEOUS_STANDING",
                    "RUN_WALKING",
                    "RUN_STANDING",
                    "WALKING_FAST_STANDING",
                    "ELEVATOR_UP_STANDING",
                    "ELEVATOR_DOWN_STANDING",
                    "WALKING_IN_DOOR_STANDING",
                    "DISTRACTED_WALKING_STANDING"
]
